apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    orgId: 1
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus

  - name: MariaDB
    type: mysql
    access: proxy
    url: $GF_DATABASE_HOST
    user: grafana
    database: grafana
    orgId: 1
    basicAuth: true
    isDefault: false
    jsonData:
      keepCookies: [ ]
    secureJsonData:
      password: $GF_DATABASE_PASSWORD
    readOnly: true
    editable: true

  - name: Postgres
    type: postgres
    url: http://postgres:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: $GF_DATABASE_PASSWORD
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
      timescaledb: false

  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    orgId: 1
    url: http://victoriametrics:8428
    isDefault: true

  - name: VictoriaMetrics-2
    type: prometheus
    access: proxy
    orgId: 1
    url: http://victoriametrics-2:8428
    isDefault: true
